# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Diary Posts', folder: 'pages', file: 'diary-posts.html'}
- {name: 'Where are we?', folder: 'pages', file: 'where.html'}
- {name: 'Other', folder: 'pages', file: 'other.html'}
- {name: 'Pictures', folder: 'pages', file: 'pictures.md'}
- {name: 'Acknowledgments', folder: 'pages', file: 'acknowl.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
