---
layout: misc
title: Other
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(readxl)
library(wordcloud)
library(ggrepel)
```

# What else was on our minds?  

In one homework assignment, students were asked to web scrape quotes from the [Brainy Quote](https://www.brainyquote.com/ "Brainy Quote") website.  What terms did we search?  What quotes did we find?

### Searched terms

```{r, message=FALSE, warning = FALSE, fig.width = 8, fig.height = 8}
Stat231_PS5_info <- read_excel("C:/Users/kcorreia/Dropbox (Amherst College)/Teaching/Spring 2020/Stat231/Calendar Project/Stat231_PS5_info.xlsx") 

Stat231_PS5_info2 <- Stat231_PS5_info %>%
  filter(is.na(Quote_Search)==FALSE & str_detect(Quote_Search, "NONE") == FALSE)

tb <- table(c(Stat231_PS5_info2$Quote_Search, "winston churchill", "resilience"))

set.seed(15)
wordcloud(names(tb), as.numeric(tb)
          #, min.freq=20
          #, max.words=50
          # plot the words in a random order
          , random.order=T
          # specify the range of the size of the words
          , scale=c(4,2)
          # specify proportion of words with 90 degree rotation
          , rot.per=.15
          # colors words from least to most frequent
          # blues
          , colors = c("#2171b5","#6baed6","#aaaaaa", "#000066", "#00004c")
          # font family
          , family="sans")
          #, vfont = c("sans serif", "plain"))
```


### Quotes

```{r}
quotes0 <-  read.csv("C:/Users/kcorreia/Dropbox (Amherst College)/Teaching/Spring 2020/Stat231/Calendar Project/all_quotes.csv") %>%
  filter(person != "KAT") %>%
  mutate(length = str_length(quote)
         , together = paste('"', as.character(quote), '" --'
                          , as.character(person), sep="")
         , quote = as.character(quote)
         , person = as.character(person)) %>%
  select(-X) %>%
  distinct()

# quotes0 %>% summarize(max(length))

search_vec <- as.character(unique(quotes0$search_term))
color_vecs <- data.frame(palette = rep(c(1:5), each=5)
                          , hexcode = as.character(c(
                              # Renewal theme
                              c("#2a2d48", "#bdbec6", "#9689e6", "#4b55ad", "#707186")
                              # AK stara strona
                              , c("#24a6b4", "#009cb2", "#007f9f", "#363636", "#434343")
                              # color supersport #1
                              , c("#00ceff", "#313036", "#ffb787", "#ff4133", "#96abff")
                              # Siahara Shyne Carter Old School
                              , c("#b98888", "#f16e6e", "#83c9b5", "#9a9db3", "#c4b8b1")
                              # fire to ice
                              , c("#12b84f", "#0d579b", "#4f5b96", "#4c3d79", "#643f7d"))))

set.seed(20200428)
for (i in 1:length(search_vec)){

  color_palette0 <- color_vecs %>% 
      filter(palette == (i%%5 + 1))
    
  color_palette <- as.character(color_palette0$hexcode)
 
  quotes_subset0 <- quotes0 %>%
    filter(search_term == search_vec[i]) %>%
    arrange(length) %>%
    slice(1:6) %>%
    mutate(x = row_number()*10
           , y = 100 - row_number()*10)

  quotes_subset <- quotes_subset0 %>%
           mutate(colorch = sample(color_palette, size = nrow(quotes_subset0)
                                   , replace = TRUE)
                 , sizech = sample(4:6, size = nrow(quotes_subset0)
                                    , replace = TRUE))
 
  plot <- ggplot() + 
      ylim(0,100) +
      xlim(0,100) +
      ggtitle(str_to_title(search_vec[i])) + 
      geom_text_repel(data=quotes_subset
                        , aes(x = x, y = y
                              , label=paste0('"', quote, '"')
                              , color = colorch)
                              #, box.padding = 2
                              , seed = i
                              , segment.alpha = 0) +
                              #, size = sizech)) +
      theme_void() + 
      theme(plot.title = element_text(size = 30, face = "bold"
                                      , color = sample(color_palette, size=1))
            , legend.position = "none") 
  
  print(plot)
}
```


```{r OLD, eval = FALSE, include = FALSE}
quotes0 <-  read.csv("C:/Users/kcorreia/Dropbox (Amherst College)/Teaching/Spring 2020/Stat231/Calendar Project/all_quotes.csv") %>%
  filter(person != "KAT") %>%
  mutate(length = str_length(quote)
         , together = paste('"', as.character(quote), '" --'
                          , as.character(person), sep="")
         , quote = as.character(quote)
         , person = as.character(person)) 

search_vec <- as.character(unique(quotes0$search_term))
color_vecs <- data.frame(palette = rep(c(1:5), each=5)
                          , hexcode = as.character(c(
                              # Renewal theme
                              c("#2a2d48", "#bdbec6", "#9689e6", "#4b55ad", "#707186")
                              # AK stara strona
                              , c("#24a6b4", "#009cb2", "#007f9f", "#363636", "#434343")
                              # color supersport #1
                              , c("#00ceff", "#313036", "#ffb787", "#ff4133", "#96abff")
                              # Siahara Shyne Carter Old School
                              , c("#b98888", "#f16e6e", "#83c9b5", "#9a9db3", "#c4b8b1")
                              # fire to ice
                              , c("#12b84f", "#0d579b", "#4f5b96", "#4c3d79", "#643f7d"))))

set.seed(20200428)
for (i in 1:length(search_vec)){
  quotes_subset <- quotes0 %>%
    filter(search_term == search_vec[i]) %>%
    arrange(length) %>%
    slice(1:6)
  
  color_palette0 <- color_vecs %>% 
    filter(palette == (i%%5 + 1))
  
  color_palette <- as.character(color_palette0$hexcode)
  
  plot <- ggplot() + 
    ylim(0,100) +
    xlim(0,100) +
    ggtitle(str_to_title(search_vec[i])) + 
    theme_void() + 
    theme(plot.title = element_text(size = 30, face = "bold"
                                    , color = sample(color_palette, size=1)))
  for (j in 1:nrow(quotes_subset)){
    plot <- plot +
       annotate("text",  size = sample(3:6, size=1)
                , x = sample(10:90, size=1)
                , y = sample(10:90, size=1)
                , label = paste0('"', quotes_subset[j, "quote"], '"')
                , color = sample(color_palette, size=1))
  }    

  print(plot)
}

```
